DROP DATABASE IF EXISTS TPCH
GO

-- CREATE DATABASE [TPCH]
-- GO
CREATE DATABASE [TPCH]
ON
(NAME = tpch_data,
    FILENAME='/path/to/data/'
)
LOG ON
(NAME = tpch_log,
        FILENAME='/path/to/log/'
)
GO

USE TPCH
GO

CREATE TABLE [dbo].[nation](
    [N_NationKey] [int] NOT NULL,
    [N_Name] [char](25) NOT NULL,
    [N_RegionKey] [int] NOT NULL,
    [N_Comment] [varchar](152),
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[region](
    [R_RegionKey] [int] NOT NULL,
    [R_Name] [char](25) NOT NULL,
    [R_Comment] [varchar](152),
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[part](
    [P_PartKey] [int] NOT NULL,
    [P_Name] [varchar](55) NOT NULL,
    [P_Mfgr] [char](25) NOT NULL,
    [P_Brand] [char](10) NOT NULL,
    [P_Type] [varchar](25) NOT NULL,
    [P_Size] [int] NOT NULL,
    [P_Container] [char](10) NOT NULL,
    [P_RetailPrice] [decimal](15, 2) NOT NULL,
    [P_Comment] [varchar](23) NOT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[supplier](
    [S_SuppKey] [int] NOT NULL,
    [S_Name] [char](25) NOT NULL,
    [S_Address] [varchar](40) NOT NULL,
    [S_NationKey] [int] NOT NULL,
    [S_Phone] [char](15) NOT NULL,
    [S_AcctBal] [decimal](15, 2) NOT NULL,
    [S_Comment] [varchar](101) NOT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[partsupp](
    [PS_PartKey] [int] NOT NULL,
    [PS_SuppKey] [int] NOT NULL,
    [PS_AvailQty] [int] NULL,
    [PS_SupplyCost] [decimal](15, 2) NOT NULL,
    [PS_Comment] [varchar](199) NOT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[customer](
    [C_CustKey] [int] NOT NULL,
    [C_Name] [varchar](25) NOT NULL,
    [C_Address] [varchar](40) NOT NULL,
    [C_NationKey] [int] NOT NULL,
    [C_Phone] [char](15) NOT NULL,
    [C_AcctBal] [decimal](15, 2) NOT NULL,
    [C_MktSegment] [char](10) NOT NULL,
    [C_Comment] [varchar](117) NOT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[orders](
    [O_OrderKey] [int] NOT NULL,
    [O_CustKey] [int] NOT NULL,
    [O_OrderStatus] [char](1) NOT NULL,
    [O_TotalPrice] [decimal](15, 2) NOT NULL,
    [O_OrderDate] [datetime] NOT NULL,
    [O_OrderPriority] [char](15) NOT NULL,
    [O_Clerk] [char](15) NOT NULL,
    [O_ShipPriority] [int] NOT NULL,
    [O_Comment] [varchar](79) NOT NULL,
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[lineitem](
    [L_OrderKey] [int] NOT NULL,
    [L_PartKey] [int] NOT NULL,
    [L_SuppKey] [int] NOT NULL,
    [L_LineNumber] [int] NOT NULL,
    [L_Quantity] [decimal](15, 2) NOT NULL,
    [L_ExtendedPrice] [decimal](15, 2) NOT NULL,
    [L_Discount] [decimal](15, 2) NOT NULL,
    [L_Tax] [decimal](15, 2) NULL,
    [L_ReturnFlag] [char](1) NOT NULL,
    [L_LineStatus] [char](1) NOT NULL,
    [L_ShipDate] [datetime] NOT NULL,
    [L_CommitDate] [datetime] NOT NULL,
    [L_ReceiptDate] [datetime] NOT NULL,
    [L_ShipInstruct] [char](25) NOT NULL,
    [L_ShipMode] [char](10) NOT NULL,
    [L_Comment] [varchar](44) NOT NULL,
) ON [PRIMARY]
GO

ALTER TABLE REGION ALTER COLUMN R_REGIONKEY INT NOT NULL;
GO
ALTER TABLE REGION ADD PRIMARY KEY (R_REGIONKEY);

ALTER TABLE NATION ALTER COLUMN N_NATIONKEY INT NOT NULL;
GO
ALTER TABLE NATION ADD PRIMARY KEY (N_NATIONKEY);


ALTER TABLE NATION
ADD CONSTRAINT NATION_FK1 FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);

ALTER TABLE PART ALTER COLUMN P_PARTKEY INT NOT NULL;
GO
ALTER TABLE PART ADD PRIMARY KEY (P_PARTKEY);

ALTER TABLE SUPPLIER ALTER COLUMN S_SUPPKEY INT NOT NULL;
GO
ALTER TABLE SUPPLIER ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE SUPPLIER
ADD CONSTRAINT SUPPLIER_FK1 FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY);

ALTER TABLE PARTSUPP ALTER COLUMN PS_PARTKEY INT NOT NULL;
ALTER TABLE PARTSUPP ALTER COLUMN PS_SUPPKEY INT NOT NULL;
GO
ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);

ALTER TABLE CUSTOMER ALTER COLUMN C_CUSTKEY INT NOT NULL;
GO
ALTER TABLE CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_FK1 FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY);

ALTER TABLE LINEITEM ALTER COLUMN L_ORDERKEY INT NOT NULL;
ALTER TABLE LINEITEM ALTER COLUMN L_LINENUMBER INT NOT NULL;
GO
ALTER TABLE LINEITEM
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);

ALTER TABLE ORDERS ALTER COLUMN O_ORDERKEY INT NOT NULL;
GO
ALTER TABLE ORDERS ADD PRIMARY KEY (O_ORDERKEY);

ALTER TABLE PARTSUPP
ADD CONSTRAINT PARTSUPP_FK1 FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY);

ALTER TABLE PARTSUPP
ADD CONSTRAINT PARTSUPP_FK2 FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY);

ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_FK1 FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT LINEITEM_FK1 FOREIGN KEY (L_ORDERKEY)  REFERENCES ORDERS(O_ORDERKEY);

ALTER TABLE LINEITEM
ADD CONSTRAINT LINEITEM_FK2 FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY);
GO

-- indexes on the foreign keys

CREATE NONCLUSTERED INDEX IDX_SUPPLIER_NATION_KEY ON SUPPLIER (S_NATIONKEY);

CREATE NONCLUSTERED INDEX IDX_PARTSUPP_PARTKEY ON PARTSUPP (PS_PARTKEY);
CREATE NONCLUSTERED INDEX IDX_PARTSUPP_SUPPKEY ON PARTSUPP (PS_SUPPKEY);

CREATE NONCLUSTERED INDEX IDX_CUSTOMER_NATIONKEY ON CUSTOMER (C_NATIONKEY);

CREATE NONCLUSTERED INDEX IDX_ORDERS_CUSTKEY ON ORDERS (O_CUSTKEY);

CREATE NONCLUSTERED INDEX IDX_LINEITEM_ORDERKEY ON LINEITEM (L_ORDERKEY);
CREATE NONCLUSTERED INDEX IDX_LINEITEM_PART_SUPP ON LINEITEM (L_PARTKEY,L_SUPPKEY);

CREATE NONCLUSTERED INDEX IDX_NATION_REGIONKEY ON NATION (N_REGIONKEY);
GO
